apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-replicaset
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: dashhhok/frontend-md:latest
          envFrom:
            - configMapRef:
                name: front-config
          ports:
            - containerPort: 80
