apiVersion: v1
kind: ConfigMap
metadata:
  name: template-config
  labels:
    tier: template-server
data:
  GATEWAY_PORT: "8001"
  DB_DRIVER: postgres
  DB_HOST: template-db
  DB_PORT: "5432"
<<<<<<< HEAD
  DB_USER:
  DB_PASSWORD:
  DB_NAME:
=======
  DB_USER: postgres
  DB_PASSWORD: ttttt
  DB_NAME: postgres
>>>>>>> origin
  DB_SSLMODE: disable
  MIGRATION_URL: file://migrate
