apiVersion: v1
kind: Service
metadata:
  labels:
    tier: template-server
  name: template-server
spec:
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    tier: template-server
  type: NodePort
